### ISSUE TITLE
images for the wiki

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RetroAchievements.github.io#1]
Although very useful, the github wiki tool doesn't provide a way to host images.

Then we can use this issue here for the *github image hosting hack* and put here the images we need in the wiki.

Just add a comment on this issue thread attaching the image file you need. It will generate a markdown link to the image, like this one:
```
![memory_inspector](https://user-images.githubusercontent.com/8508804/32601361-83b8d962-c529-11e7-9e90-85fe2edc6f45.png)
```

Now you can copy this markdown link and use on your wiki page.

Quoting what I read ]where I learned this trick](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/):

> **I admit this is a *HACK* only useful until GitHub finally provides a more intuitive upload feature. But until that happens… enjoy!** 

---
![memory_inspector](https://user-images.githubusercontent.com/8508804/32601361-83b8d962-c529-11e7-9e90-85fe2edc6f45.png)

![achievement_editor](https://user-images.githubusercontent.com/8508804/32601359-8373419a-c529-11e7-9958-fbdb28dcc44d.png)

![achievement_set_dialog](https://user-images.githubusercontent.com/8508804/32601360-83970cba-c529-11e7-9e24-d6547e361128.png)

![testing_achievements](https://user-images.githubusercontent.com/8508804/32601362-83dcb788-c529-11e7-8df9-b79038408909.png)

![testing_achievements2](https://user-images.githubusercontent.com/8508804/32601363-83fced8c-c529-11e7-885f-97d64b0384e5.png)

**Comment by celerizer** [comment]
![nes_mem_mirror](https://user-images.githubusercontent.com/33245078/32608415-e8bd2cf8-c521-11e7-8da5-22c9e09efd8c.png)

**Comment by celerizer** [comment]
![817d6ec060c1fec958068ccbcba5a3a5](https://user-images.githubusercontent.com/33245078/32610144-755a0442-c527-11e7-9bbb-eb5a4d7b8e6d.png)

**Comment by meleu** [comment]
let's move to https://github.com/RetroAchievements/docs/issues/1
